import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useMediaQuery, useViewportSize } from "src/lib/mantine";

import { Button } from "@mantine/core";

const Home: NextPage = () => {
  const { width } = useViewportSize();
  const largerThanXs = useMediaQuery("xs");
  const largerThanSm = useMediaQuery("sm");
  const largerThanMd = useMediaQuery("md");
  const largerThanLg = useMediaQuery("lg");
  const largerThanXl = useMediaQuery("xl");
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>Hello</main>
    </div>
  );
};

export default Home;
